---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgB8o9ilubeW5tTG7PeGr0N+4kq2ENxf5WivRE+T/yyvJXwPCGpfaRHLGMM3xqtS30oygQYVVBrpRJfMWFUYRgwOqw58/LmYx8MaCbL5wkD94gDKHKunZ9zi/lbwRO+bgr6xKBN9LCg9ccgmAkdqkzfq2XNfM77KKlZkPncYo/AlK4ko/VBaDeLnOm1zR7mHC3aCd60LQJ56+ccMmRwGAPXXGvDuI8cV63xLjwnXrb124HOLDYmF2ENfnMzUF94A0xgI4eYMdtFrqOqyG8on26FiMuHLjV7lj6TC8a/TcbZBinprNRBYky+yEyPibH8EMhkK0GCn01+VgYbg7L8eONjIjwHxg4fIPOkMOxCbtxqHFB9GLq4hK2M8dA3vMUjTdh2IahPabB0C6qM+iY3S8sW8fWZn2210C5sad+BcGSdzn7thy5XtPjhr5gJMSvJCDNv+HceVFAdbriPe8V9qACJSogYlX4lv33/s1yy6IBtAOF/OaOK/+dkaW4KZmbNle1cme55cWXYddF2R/ue0Owmojed0hDKJxUqXQ9VK8vWOgq8pqhHnc2/8RRowOiBI+JHmkgbwHNvUKdtyL58l4U/gmxK8YH0HXkbNuQ+FLk6TNCuxv7J9jHxE2o1S7xly4xlFGPUoCV+3SJFIUhghqrDCwLypHP5TRETqXKWKMsTCFcVdWUZewCxI1Ad5Cbr/Z0fXxPrnIhaayP9ZrqVnXMejxzPMHBkKZl6wABuoKcp5dODU0fDpaPd+pVBlnHof
    TELEGRAM_CHAT_ID: AgB2EDp9kEiQ2SDD3wgYASX9vIJDnb805mQ7Cnw4OgHzetaxIBRpaI0/qfwvaBmHv205b0yzw0TXpEZMKY+eTqnSnDvKhZ1u9DdmPO2gSrouXXJdZuLJ/aCDO10PfXYzS0fXY+A8xhpg8z6qDjB5d+9Rj00uPnXtJ3LnyQAybOnRuq5JjQcT4hqjLplx9xLpvVIgEUwSJtJRl8Nyf50DfHpk1XkRaia7ZaPVHYRAGQCP9qngIp+Qt7khufwmEs05mH1WyOVQbEObys/otNM2y+yoTi8vL3Rw2Pm3p/f6xUyMpFHWB0fyxm93vGI7Wd4RTDS0QDDEvfZWVTPJ+eO8hq08u3XceQLLtBUllkT85iUqVdbEPARo6hn+KEhheuxuO8xCIBckNEmZKdprv3U+FW79baizl5EykvsMFi6CDaVW9iLfDLJOa8PY5owQc1jdCvGBC160cPUO7DUaq6Vj01loMymLwV/Eaw9niHrKTPRat5EvPCEh2h+l2SjgYxHEEj1zcEFnbmLhig25ZuEA3yhUQdarWINQ6jPNy3MJcByHC30Ls5ec1NRDg8Hznv+r6904eVbG+BqIBqBoWNDG6RCA6B0YcM4WZcGIEX+4T53K+4aoBxNp/Q+znngr0SJcUKixYx9ARKSO9hJJaU08vSWUU8vr4jC67DocX/cGPq3xh/9mlm73O134Y9wGIPm8s0m8lTFn4ZyITTNHdw==
  template:
    metadata:
      name: grafana-telegram-secret
      namespace: monitoring
