---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgCa6QszrczvjIFcbYpleLK7MuDrQRxxdFX7zJDDeThM22V+qBlT4vGH54ctZ4eZDOx65pUQbPr3I3n+jMFAFgKBLW3Y1VWPUPQBnwl3zBCFwSY1OqgG/OSi+X6MnK7bHxlY6cLMBMOZob43Gh3aUwtI2uIp74nvtDXzIJdpMbbAB7EY/2flXpEh3jF4vgD8IqwpaYqPnAP+OKeOJ+OAx1IPs75E5qWJ0wprZnLGyXHDE2o4FehxXuwAigFsoF0kZrsVOFQRnXvYu/VdyjcVje4dPXRO53R54U9Fi8Q44cWzKarQalffsQiCH/OwDa4q202o7538ElTchlZyrYoo2NkqNw58eazyCEFu0ReTvWvmHKf9h62T20Hoem64ARzsg/jDoZAXY27fEBHq4Us1GeG9B7uoDQF9MTBEJeuRecKXnOheFtFZmRnve28Q8MRes5OwUPcOzRveujUQdsc0tyqLyYtGMR/MrjZfP3096WXu63tz12kNsurkXuNQdxxeGxSx/wGlvxRSAqGWLNTPt8r6IQ1X/MIXjduE+gEY/P3qFj2+c8BewZLKiyyVxkW1y8wkCsGvTyRbm7jkqgXuAME/NoP4q+FsWi/Eu8nSXT3W6gmwgD3Nue1irAfmtcPDmc5i1WncNk76yEUrWR/eE6VB8TrVqpSv/XGnshPWi99TbscbwFD2i3FUcZyGmVux+70CqWbLNro/8ftIsjKfQ9VCtNpDriLZ9HaERSGC009W93DS4T+LG0rH8LkUEK+U
    TELEGRAM_CHAT_ID: AgBoSEXECaNKvnmXr1ytb1Adtnl1GjvmGYJdST5gW8UUSPJFmpdeG7Y+sed3dZ81Ic1OIloM2wSjmcav1RnrFfTg5OzAoQsKz3Ca8omML/TzTT1zOmOwCPPv0bbS3G5/b/7uUZ25ArqR/f83YWI9eYZW7pzlohoaoNLtl+giSbr7I2hM09XddEdSKecfkDf6vcrMsOE7sceAO0jN63TgwydCPDGQxmlBLN26aFbjZIWglXDuBxnMITcp/wvTOMpvMRxOfOi1Fy1+TfM3ieR2QZBIrtJb0LyMr9m2W9dhXodzrASv+CN3Sdf6wZNiN8il+hIph4TvVrvWyplG/kFJe/yOJHSlAYCLcSYL4KlXFywN7+9o5OzGUqgavBHSEMY14ql1JBx4Knl6xWbNUw/fibTBebxlxvjxs3ogIaROtmqFf/1n6lgLCGhPFxc+CbpnE2FNEKukGZjmLwdjDaIL1N6fZWXYgP1ueATAr0/ya2f9TPuJxkctakJAVc8GCDZShLazmltzn2j+M1EfspFVnBaGxZNEJtijb5wq1zxJL3dPDQKGZif/ZkBHYr2BMgP47y3F+rTaSe88f/h7XyxL34tKrI0GMD975nH3lpTmckUncwCjjm44zaLCasc4EAA/ebILYcf/FvEigIP+ez2OWmbLq2GjuyiR5+ajVxolHbTJJHZFiG4roqJ3+AfEN9GptgLKGEmDG8wRHH42jeOT
  template:
    metadata:
      name: grafana-telegram-secret
      namespace: monitoring
