---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgACbZCb36RlIxA1P8bR7Xa7c26SzZF6ERHK4QGnz+pAiefj1KjLsO0YABTCWX5uXN+CkgzlwAhH/huqYzhn5gHwtJRPXgdEYBxy8hyWS9VksEzDkv/iVypoyFzEb5K7cM9c2FaYrTe5Ca5bjlsQpTPXutwUZ7v5EK3gH2e7icFci+hWqNKFqQhC/+mqR+bh/BH5RiVnm95bcNhmaUXo1K/WcO8NFTiW6j740MyuHAdQDcyuZOz1Ie9lefNuSfcHNzxm9gkatImadc18hjiL3TYYXZqIcz4G79xg6w6WdDseWyxXuwpYHBDTIg+IvxuQqjUf0wl+TebL+NrTrDDAXMt5oEKpAL7t0HsIz7pLdPR/xZWyl/aaY81Jmc2gJBKaGGk582j4rVb5a01LCvIxJqyGWW4L0fxcIFcWFMolEDEtHa9TLtaET796RRv68hu+3Mo3TI/x+UGHB/+7ybl8maqMLMDXyV9DDf6n3SZjdoB9lMTyDKluWpAw9cHp3QJVE94oIgCnIgLDq44F7rb5xGB0JyxEsza5wgU2QzIyGgRE8fG5Ha7O6J8Ls57P+h8e6qCzqz6fEV2bixPI5bnQXbF/FI+RXpineLSZuUw9xIplwwfnFWz5OV9iKw3mk/SPq0ERQfl7ZfLiSEZtLZvHiIC08tYavJSD132ZAdDBD1fmbxcDhbyfMJWhwUA3XtMX0pXDul2YprQ8aNzy0Yxor+4kBfl170/MqtaL+YQ1nUzZL+AbcXWJDIaRmJCpiDZV
  template:
    metadata:
      name: grafana-telegram-secret
      namespace: monitoring
