---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts-kubernetes-pods
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # your ruleSelector label
spec:
  groups:
    - name: pod.availability
      rules:
        - alert: KubePodNotReady
          annotations:
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready
              state for longer than 15 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
            summary: Pod has been in a non-ready state for more than 15 minutes.
            dashboard_url: "https://monitoring-monitoring-stack-grafana-ingress.tail3f1bda.ts.net/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?var-namespace={{ $labels.namespace }}&var-pod={{ $labels.pod }}&from=now-1h&to=now"
          expr: |
            sum by (namespace, pod, cluster) (
              max by(namespace, pod, cluster) (
                kube_pod_status_phase{job="kube-state-metrics", phase=~"Pending|Unknown|Failed"}
              ) * on(namespace, pod, cluster) group_left(owner_kind) topk by(namespace, pod, cluster) (
                1, max by(namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"})
              )
            ) > 0
          for: 15m
          labels:
            severity: warning