---
extends: default

rules:
  line-length:
    max: 160
    level: warning
    allow-non-breakable-inline-mappings: true

  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: true

  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

ignore: |
  .git/
  .tox/
  node_modules/
  charts/*/charts/
  playbooks/vars/tailscale-secrets.yaml
