[tox]
envlist = ansible-lint, yaml-lint
skipsdist = true

# ──────────────────────────────────────────────
# Ansible Lint
# ──────────────────────────────────────────────
[testenv:ansible-lint]
deps =
    ansible-lint
commands =
    ansible-lint --profile production --config-file {toxinidir}/.ansible-lint {posargs}

# ──────────────────────────────────────────────
# YAML Lint
# ──────────────────────────────────────────────
[testenv:yaml-lint]
deps =
    yamllint
commands =
    yamllint -c .yamllint.yml . {posargs}