---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-argo-cd.yaml
  - path: patch-monitoring-stack.yaml
  - path: patch-longhorn.yaml
