---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            host: argocd
            tls: true
            ingressClassName: tailscale
          metrics:
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: monitoring-stack
        controller:
          metrics:
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: monitoring-stack
            enabled: true
        repoServer:
          metrics:
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: monitoring-stack
            enabled: true
        applicationSet:
          metrics:
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: monitoring-stack
            enabled: true
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.17
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
