---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-cd.yaml
  - cert-manager.yaml
  - longhorn.yaml
  - monitoring-stack.yaml
  - cnpg.yaml
  - metric-server.yaml
  - kargo.yaml
