---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-root
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-manifests/monitoring/alerts
    repoURL: https://gitlab.com/Sonal.work/myhomelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
