---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        alertmanager:
          ingress:
            enabled: true
        grafana:
          ingress:
            enabled: true
        prometheus:
          ingress:
            enabled: true
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 82.18.0
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
