---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: tailscale
        grafana:
          ingress:
            enabled: true
            ingressClassName: tailscale
          envFromSecret: grafana-telegram-secret
          alerting:
            contactpoints.yaml:
              apiVersion: 1
              contactPoints:
                - orgId: 1
                  name: Telegram
                  receivers:
                    - uid: telegram-uid
                      type: telegram
                      settings:
                        bottoken: $TELEGRAM_BOT_TOKEN
                        chatid: $TELEGRAM_CHAT_ID
                      disableResolveMessage: false
            notification_policy.yaml:
              apiVersion: 1
              policies:
                - orgId: 1
                  receiver: Telegram
                  group_by: ["grafana_folder", "alertname"]
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 4h
        prometheus:
          ingress:
            enabled: true
            ingressClassName: tailscale
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 82.18.0
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
