---
- name: Configure kargo resource for kargo app
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/kargo.yaml
    - vars/cluster.yaml
  environment:
    KUBECONFIG: "{{ local_kubeconfig }}"

  tasks:
    - name: Create kargo namespace for kargo app
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: kargo

    - name: Create a secret for kargo admin user
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: kargo-admin-secret
            namespace: kargo
          type: Opaque
          stringData:
            ADMIN_ACCOUNT_PASSWORD_HASH: "{{ kargo_admin_password_hash }}"
            ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: "{{ kargo_admin_token_signing_key }}"
