- name: Create vm
  hosts: localhost
  vars_files:
    - vars/tailscale-secrets.yaml
    - vars/cluster.yaml
  vars:
    memory_mb: 6144
    vcpus: 4
    centos_images_url: https://cloud.centos.org/centos/10-stream/x86_64/images
    centos_qcow2_image: CentOS-Stream-GenericCloud-10-latest.x86_64.qcow2

  tasks:
    - name: Check if VM already exists
      become: true
      ansible.builtin.command:
        cmd: "virsh domstate {{ item }}"
      loop: "{{ k8s_vm_names }}"
      register: existing_vms
      changed_when: false
      failed_when: false

    - name: Create missing VMs
      ansible.builtin.include_tasks: tasks/create-vm-instance.yaml
      loop: "{{ existing_vms.results }}"
      loop_control:
        loop_var: vm
      vars:
        vm_name: "{{ vm.item }}"
      when: vm.rc != 0

    - name: Get IPs for existing VMs
      become: true
      ansible.builtin.shell: |
        virsh domifaddr {{ vm.item }} --source agent 2>/dev/null | awk '/ipv4/ {print $4}' | cut -d/ -f1
      loop: "{{ existing_vms.results }}"
      loop_control:
        loop_var: vm
      register: existing_vm_ip_results
      changed_when: false
      failed_when: false
      when: vm.rc == 0

    - name: Add existing VM IPs into created_vm_ips
      ansible.builtin.set_fact:
        created_vm_ips: "{{ created_vm_ips | default({}) | combine({ item.vm.item: item.stdout_lines[1] }) }}"
      loop: "{{ existing_vm_ip_results.results }}"
      when:
        - item.skipped is not defined
        - item.stdout_lines is defined
        - item.stdout_lines | length > 1