# clone git repo for kubespray
- name: Prepare and run Kubespray
  hosts: localhost
  vars:
    kubespray_dir: "{{ ansible_env.HOME }}/src/kubespray"
    kubespray_inventory_dir: "{{ kubespray_dir }}/inventory/mycluster"
    kubespray_venv: "{{ kubespray_dir }}/.venv"
    network_plugin: "cilium"

  tasks:
  - name: Create src directory
    ansible.builtin.file:
      state: directory
      path: "{{ ansible_env.HOME }}/src"

  - name: Clone kubespray repo
    ansible.builtin.git:
      repo: https://github.com/kubernetes-sigs/kubespray.git
      dest: "{{ kubespray_dir }}"

  - name: Create k8s inventory directory
    ansible.builtin.file:
      state: directory
      path: "{{ kubespray_inventory_dir }}"
      mode: '0755'

  - name: Copy inventory sample to mycluster
    ansible.builtin.copy:
      src: "{{ kubespray_dir }}/inventory/sample/"
      dest: "{{ kubespray_inventory_dir }}/"
      mode: '0755'
      remote_src: true

  - name: Create inventory file
    ansible.builtin.template:
      src: files/templates/inventory.ini.j2
      dest: "{{ kubespray_inventory_dir }}/inventory.ini"
      mode: '0644'

  - name: Create network plugin configuration file
    ansible.builtin.template:
      src: files/templates/k8s-cluster.j2
      dest: "{{ kubespray_inventory_dir }}/group_vars/k8s-cluster.yml"
      mode: '0644'


  - name: Ensure kubespray venv exists and requirements are installed
    ansible.builtin.pip:
      requirements: "{{ kubespray_dir }}/requirements.txt"
      virtualenv: "{{ kubespray_venv }}"
      virtualenv_command: "python3 -m venv"
      state: present

  - name: Check vm status
    become: true
    ansible.builtin.command: "virsh domstate {{ item }}"
    loop:
      - "{{ k8s_master1_hostname }}"
      - "{{ k8s_master2_hostname }}"
      - "{{ k8s_master3_hostname }}"
    register: vm_status
    changed_when: false

  - name: Fail if any of the VMs are not running
    ansible.builtin.fail:
      msg: "One or more VMs are not running. Please start all VMs before proceeding."
    when: >
      (
        vm_status.results
        | selectattr('stdout', 'match', '^running\\s*$')
        | list
        | length
      ) != 3

  - name: Wait for ssh to be available on all hosts
    ansible.builtin.wait_for:
      host: "{{ item }}"
      port: 22
      timeout: 300
    loop:
      - "{{ k8s_master1_ip }}"
      - "{{ k8s_master2_ip }}"
      - "{{ k8s_master3_ip }}"
