---
- import_playbook: create-vm.yaml
  tags:
    - create-vm

- import_playbook: prerequisite-k8s.yaml
  tags:
    - prerequisite

- import_playbook: cluster.yml
  tags:
    - cluster-creation

- import_playbook: install-argocd-tailscale.yaml
  tags:
    - install-argocd
    - install-tailscale

- import_playbook: install-infra-apps.yaml
  tags:
    - install-infra-apps
